// Code generated by go generate; DO NOT EDIT.
package nsq

import (
	"github.com/minus5/nsqm"
	"github.com/minus5/nsqm/example/rpc_with_code_generator/service/api"
)

var (
	reqTopic = "service.req"
)

func Client(cfg *nsqm.Config) (*api.Client, error) {
	rpcClient, err := nsqm.NewRpcClient(cfg, reqTopic)
	if err != nil {
		return nil, err
	}
	return api.NewClient(rpcClient), nil
}

type Closer interface {
	Stop()
	Close()
}

func Server(cfg *nsqm.Config, srv nsqm.AppServer) (Closer, error) {
	return nsqm.NewRpcServer(cfg, reqTopic, srv)
}
