// Code generated by go generate; DO NOT EDIT.
package service

import (
	"context"
	"fmt"

	"github.com/minus5/nsqm/example/rpc_with_consul_discovery/service/api"
)

func (s *Service) Serve(ctx context.Context, method string, buf []byte) ([]byte, error) {
	switch method {
	case api.MethodAdd:
		var req api.TwoReq
		if err := api.Unmarshal(buf, &req); err != nil {
			return nil, err
		}
		rsp, err := s.Add(ctx, req)
		if err != nil {
			return nil, err
		}
		return api.Marshal(rsp)
	case api.MethodCube:
		var req int
		if err := api.Unmarshal(buf, &req); err != nil {
			return nil, err
		}
		rsp, err := s.Cube(ctx, req)
		if err != nil {
			return nil, err
		}
		return api.Marshal(rsp)
	case api.MethodMultiply:
		var req api.TwoReq
		if err := api.Unmarshal(buf, &req); err != nil {
			return nil, err
		}
		rsp, err := s.Multiply(ctx, req)
		if err != nil {
			return nil, err
		}
		return api.Marshal(rsp)
	default:
		return nil, fmt.Errorf("unknown method %s", method)
	}
}
